git:
  depth: 5

env:
  global:
    - secure: RK90rQ2zqYxGlG7vxb4XyknUfrIGeG4s/ZLLlm9n990cczg1opJdmS+O+RM+Wxn0vOffSHYuXf2EmcTjBbqwWOUe8Fynv9pOjLjLVlpcUD6xWqmottjwuROZN6FVQjicBQeXdLzf/WehgDQ7EDVxfp6YRB6esZcbpvVi3AgQZ7h3IEKi6rHhda7H6oQugO4tMbrYK8lNzvJFfG5J/isy4XMJDkM7tD2wbqu2EIGCwoM474wNKJmXSx9+54u95oi5Lx08aMDbKDRK9AjK8A5KfEbIoBonMnfjYcWfYJfUlzZwgiAtxixC9dYyObOW8RT18YXdDsn3WANUYw3caZS7sv544wUTWROGj+fwgxs+N+fcPjaitswwX8cSJBBjA13wAiCQVSUXsjOofvhDtKFv3gflkLYae4pryGsP1lNLFkrkYMOhoRbP572eOEUisfSrOLuTvV3C4Z3ae8nghfYNXGiCoxYX/ska2NegYPnYUkmLmEeOSExd+fc+8n7Q1t+ER9mRfp/kAxChyoioaLWiq4GgmzKgURg6pmpWRmOIJ+sGx/AJ39tRZAMDNOqdedmYmRsBRuy/HF38wXysxSOh9ukV243wi+szEF5XR/zg6fJJYfPzTKcXFvYGJCPE0ccHgH/wG/RVWKT1dWs7iWrY8IudupkF8dN/DpvoH2l2KmM=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: mitchellkrog@gmail.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/Ultimate.Hosts.Blacklist
    - GIT_BRANCH: master
    - PYFUNCEBLE_AUTO_CONFIGURATION: PyFunceble
    - PYFUNCEBLE_OUTPUT_DIR: /tmp/
    - PYTHON_VERSION: "3.8.1"

dist: bionic
language: generic

install:
  - export PATH="${HOME}/miniconda/bin:${PATH}"
  - if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O ${HOME}/miniconda.sh; else wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ${HOME}/miniconda.sh; fi
  - bash ${HOME}/miniconda.sh -b -p ${HOME}/miniconda
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda config --add channels conda-forge
  - conda update -q conda
  - conda create -q -n ultimate-environment python="${PYTHON_VERSION}"
  - source activate ultimate-environment
  - python --version --version
  - pip --version
  - conda --version
  - pip install ultimate-hosts-blacklist-central-repo-updater

script:
  - ultimate-hosts-blacklist-central-repo-updater --version
  - ultimate-hosts-blacklist-central-repo-updater -m

notifications:
  on_success: change
  on_failure: always
